### PR TITLE
Reworked application Help

### PR DESCRIPTION
**Pull request by EddieDover**
### DRAFT
Here's the PR for the multi option method.   ( Issue #46 )

I'm by absolutely **NO** means an expert with argparse. There was a lot of trial and error here, figuring out the best way to cascade the arguments down to screen but still have the screens be modular and still support plugin screens.  However, it seems to work fine so I think this is on the right track.

That said, there were a lot of core changes and there's a chance I had tunnel vision and missed a better way of doing something.  

It needs a lot more testing and from other people so there's no bias on my part.

### CODE REVIEW

**Comment by brunobraga** [comment]
Wow, a lot of changes there.

I can run some tests here, but maybe this is a good opportunity to implement some unit testing in the code? This will help future updates.

**Comment by EddieDover** [comment]
> 
> 
> Wow, a lot of changes there.
> 
> I can run some tests here, but maybe this is a good opportunity to implement some unit testing in the code? This will help future updates.

I couldn't agree more with both statements 👍🏻

**Comment by EddieDover** [comment]
Just wanted to let you know I'm working on this. Had to rework a bit of code so I could capture screens for unit tests, but it's coming along swimmingly.

So far, tests for two screens are finished with more to come. I expect to be finished before the weekend.

image

**Comment by EddieDover** [comment]
This is coming along well, @brunobraga, if you'd like to take a look and discuss. Still not finished but I think something's coming together.

Side note. renaming termsaver and setting up internal pathing allowed me to access the module properly from a subfolder (Seems that python3 doesn't allow the same inherit includes that python2 did), also, having the .py extension allows windows to see that this is python and 'just run' when using "termsaver" in the console.

**Pull request merged**
