### PR TITLE
Add zsh completion

### PR DESCRIPTION
**Pull request by wkentaro**
image

### CODE REVIEW

**Comment by brunobraga** [comment]
I have no means to test this at the moment. Can you confirm this change also works on regular bash?

**Comment by wkentaro** [comment]
this completion file is only for zsh, so does now work on bash.

On Fri, Aug 21, 2015 at 7:09 AM, Bruno Braga <notifications@github.com>
wrote:

> I have no means to test this at the moment. Can you confirm this change
> also works on regular bash?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunobraga/termsaver/pull/20#issuecomment-133193658>.
>



-- 
和田 健太郎 / Kentaro Wada
http://wkentaro.com <http://www.wkentaro.com>

**Comment by wkentaro** [comment]
I updated the commit for completion of command options.
image

**Comment by brunobraga** [comment]
Can you check if it breaks on bash? Taking that bash is the main and
dedault application for terminals in Ubuntu/Debian, we need to ensure it is
compatible at least.

Thanks,

On Friday, 21 August 2015, Kentaro Wada <notifications@github.com> wrote:

> this completion file is only for zsh, so does now work on bash.
>
> On Fri, Aug 21, 2015 at 7:09 AM, Bruno Braga <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > I have no means to test this at the moment. Can you confirm this change
> > also works on regular bash?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/brunobraga/termsaver/pull/20#issuecomment-133193658
> >.
> >
>
>
>
> --
> 和田 健太郎 / Kentaro Wada
> http://wkentaro.com <http://www.wkentaro.com>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunobraga/termsaver/pull/20#issuecomment-133262094>.
>


-- 


*--Bruno Braga*
bruno@brunobraga.net
+61-452-212-910

**Comment by wkentaro** [comment]
it does no work on bash, because this completion file uses zsh specific functions.
zsh also support bash completion, so sourcing bash completion file like below does work.
https://github.com/wkentaro/pycd/blob/master/completion/_pycd
But in this case, the command description does not appear.

So, I think we should create another completion file for bash to support bash also.
like:
https://github.com/wkentaro/pycd/tree/master/completion

**Comment by wkentaro** [comment]
Added bash completion file.
image

**Comment by brunobraga** [comment]
Kentaro,

Thanks again. Looking better!

I just remembered why I didn't do this before... I was actually working on a plugin system to allow anyone to create add-ins without pushing to this main project... I created brunobraga/termsaver-figlet as an example on how to achieve this, and got a bit stuck on setting up the auto-complete in a way that would also capture the plugins. I am happy to push a solution forward, but would like to keep in mind for that in near future.

Any ideas?

**Comment by wkentaro** [comment]
I don't know how to create add-ins for termsaver, but
I think splitting a large project to some small repositories is a good idea if user can install all of them easily. And using pypi, we can set dependencies for each package.

**Comment by wkentaro** [comment]
any updates?

**Comment by brunobraga** [comment]
Sorry O am currently lumped with work... Will get back to you soon on that.

On Thursday, 10 September 2015, Kentaro Wada <notifications@github.com>
wrote:

> any updates?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/brunobraga/termsaver/pull/20#issuecomment-138919254>.
>


-- 


*--Bruno Braga*
bruno@brunobraga.net
+61-452-212-910

**Comment by wkentaro** [comment]
never mind. thanks.

**Comment by wkentaro** [comment]
ping

**Comment by brunobraga** [comment]
Done! Thanks

**Pull request merged**
